# ── Video ──────────────────────────────────────
profile=high-quality
#gpu-api=vulkan
hwdec=auto

scale=ewa_lanczossharp
dscale=mitchell
cscale=spline36

deband-iterations=2
deband-threshold=32
deband-range=20
deband-grain=4

# ── Audio & Language ───────────────────────────
volume-max=100
alang=jpn,ja,spa,es
slang=spa,es,es-ES
subs-with-matching-audio=no

# ── Subtitles ──────────────────────────────────
sub-font='Trebuchet MS'
sub-font-size=46
sub-border-size=1.5
sub-shadow-offset=0.8
sub-shadow-color='#000000'
sub-margin-y=40
sub-margin-x=120

# ── OSD & Window ───────────────────────────────
osc=no
title-bar=no
osd-bar=no
autofit=65%x65%

osd-font='Roboto'
osd-border-size=0.8
osd-color='#eeffffff'

script-opts=console-background_alpha=0,console-padding=16,console-corner_radius=4

# ── Misc ───────────────────────────────────────
taskbar-progress=no
keep-open=yes
idle=yes
image-display-duration=inf

# ── Screenshots ────────────────────────────────
screenshot-format=png
screenshot-directory='~/Pictures'

# ── Autoload ────────────────────────────────────
autocreate-playlist=same
directory-mode=ignore

# ── Profiles ──────────────────────────────────
[deband]
profile-desc=Sources below YUV420P10 turn on debanding
profile-cond=get("video-params/average-bpp") < 24
profile-restore=copy
deband=yes

[super-res]
profile-cond=osd_width / width >= 2.0
profile-restore=copy
glsl-shaders=~~/shaders/ArtCNN_C4F16.glsl;~~/shaders/CfL_Prediction.glsl

[extension.gif]
loop-file=inf
